name: footy_shorts
description: "Matchs Highlights."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_video_info: ^1.3.1
  video_player: ^2.8.1
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  adaptive_theme: ^3.4.1
  icons_plus: ^4.0.0
  get: ^4.6.6
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  hive: ^2.2.3
  path_provider: ^2.1.1
  image_pickers: ^2.0.4+5
  awesome_snackbar_content: ^0.1.3
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties
